[build]
  command = "npm run build"
  publish = "docs"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https: wss:;"